Email fix
ubccr/coldfront pull request #242
Opened 2020-10-20 15:49 UTC by bhatiadheeraj

2020-12-01 13:59 UTC, dsajdak requested changes

2020-12-01 13:59 UTC, dsajdak commented on coldfront/core/allocation/views.py
> +                        allocation_activate_user.send(
@bhatiadheeraj this line should actually call allocation_remove_user not allocation_activate_user.  This is sending a signal to the FreeIPA plug-in to add or remove the allocation user from unix groups.  See https://github.com/ubccr/coldfront/blob/master/coldfront/core/allocation/signals.py#L3  If you can fix that and resubmit the PR we should be good.

2020-12-04 16:20 UTC, dsajdak commented
Tested changes and all works as desired.

2020-12-04 17:34 UTC, aebruno requested changes

2020-12-04 17:34 UTC, aebruno commented on coldfront/core/allocation/views.py
> +            print(email_receiver_list)
Can we remove this debug line.

2020-12-04 19:02 UTC, aebruno approved these changes

2020-12-04 19:02 UTC, aebruno commented on coldfront/core/allocation/views.py
> +            print(email_receiver_list)
I can fix this after the merge

2020-12-04 19:02 UTC, merged