Bug Fix: Publications can be added to projects no matter how many authors they have
ubccr/coldfront pull request #377
Opened 2022-03-01 16:14 UTC by brisco17

Resolves issue #283
* If a publication is searched for by its ID in order to be added to a project, it will now be successfully added no matter how long its author field is.
* Publications like this will have its author field truncated down to 1024 characters.

2022-03-03 20:35 UTC, dsajdak requested changes
These changes fixed the error for adding a publication with an author list longer than 1024 characters.  However, once the publication is added, it can't be deleted.  

![puberror](https://user-images.githubusercontent.com/9355962/156648526-593e44bd-dbd7-4272-b567-b60d6f82a71d.PNG)

2022-03-04 13:24 UTC, aebruno commented
This may be related to #247

2022-03-09 15:57 UTC, dsajdak approved these changes

2022-03-09 15:59 UTC, dsajdak commented
This error was related to the mariaDB/mysql utf8 support.  Other testing shows these changes are good so we're going to approve it and merge.  We'll be recommending Postgres for better encoding support, specifically for scientific and math characters frequently used in publication titles.

2022-03-09 16:21 UTC, merged