Project Attributes
ubccr/coldfront pull request #466
Opened 2022-10-13 16:24 UTC by aestoltm

Reconstructed PR(#450) to see how migrations change after refactoring PR(#399) created by @RyanChang0369

2022-10-27 12:12 UTC, aebruno requested changes

2022-10-27 12:12 UTC, aebruno commented on coldfront/core/project/management/commands/add_default_project_choices.py
>              AttributeType.objects.get_or_create(name=attribute_type)
Please remove all the `delete()` calls in this file. For example: `ProjectReviewStatusChoice.objects.all().delete()`

2022-10-27 15:30 UTC, dsajdak approved these changes
All previous requests on this PR have been completed and test out well.  I have found no other issues with it and think it looks great!  Thanks @aestoltm!

2022-11-08 14:21 UTC, aebruno approved these changes

2022-11-08 14:31 UTC, merged