Refactor howto import data documentation.
ubccr/coldfront pull request #514
Opened 2023-04-06 17:28 UTC by aebruno

This commit refactors bulk data import documentation.

2023-04-07 18:10 UTC, dsajdak requested changes
Just a few minor changes, in addition to adding the PI as a user on the project and allocation

2023-04-07 18:10 UTC, dsajdak commented on docs/pages/manual/howto/importing.md
> +        "total_amount_awarded": 3000000.0,
This is missing the percent credit ("percent_credit": 20.0,) as shown in the dump above and makes the import fail.  Adding that in fixes the issue.

2023-04-07 18:10 UTC, dsajdak commented on docs/pages/manual/howto/importing.md
> +The following sections describe how you can builk import Users, Projects,
bulk is misspelled

2023-04-07 18:10 UTC, dsajdak commented on docs/pages/manual/howto/importing.md
> +The previous sections provide examples of import specific data into ColdFront.
recommend changing 'import' to 'importing'

2023-04-11 15:42 UTC, aebruno commented on docs/pages/manual/howto/importing.md
> +The following sections describe how you can builk import Users, Projects,
fixed

2023-04-11 17:23 UTC, dsajdak commented on docs/pages/manual/howto/importing.md
> +        "allocation": 5,
```suggestion
        "allocation": 2,

```

2023-04-12 14:54 UTC, dsajdak approved these changes
Just one minor typo but other than that this all works well.

2023-04-12 15:59 UTC, merged

2023-04-12 15:59 UTC, dsajdak commented on docs/pages/manual/howto/importing.md
> +$ coldfront shell < import-alloc-users.py`
```suggestion
$ coldfront shell < import-alloc-users.py

```