Plugin documentation added
ubccr/coldfront pull request #530
Opened 2023-06-05 22:46 UTC by rg663

Resolves issue #472 — Documentation to link a Django app, or plugin, to ColdFront is added to the ColdFront documentation at https://coldfront.readthedocs.io/en/latest/.

2023-06-14 19:23 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +The tutorial below assumes that you are comfortable with Django. If not, check out [these docs]("https://docs.djangoproject.com/en/4.2/intro/tutorial01/") for an introduction to how to build a Django
This link doesn't work.  I think you need to take out the quotes around the URL

2023-06-14 20:43 UTC, rg663 commented on docs/pages/plugin/how_to_create_a_plugin.md
> +The tutorial below assumes that you are comfortable with Django. If not, check out [these docs]("https://docs.djangoproject.com/en/4.2/intro/tutorial01/") for an introduction to how to build a Django
Fixed, thank you @dsajdak!

2023-06-23 18:40 UTC, dsajdak requested changes
@rg663 this all works in my testing but I did recommend some changes in the docs.  I'd also like to talk to you about how we can better recommend connecting plugins to CF.  It works to put this in the core directory but I think it might be better to recommend putting them in the plugins directory - or provide examples for both.  You may have had technical reasons to do this or it ties into your work on #537

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +    path('weekly-report/', include('coldfront.core.weeklyreportapp.urls')),
```suggestion
    path('weeklyreportapp/', include('coldfront.core.weeklyreportapp.urls')),
```
For consistency, naming the directory the same as what's in the example repo unless this is like this for a reason

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +4. In your apps' **views.py** file, add this line:
I think items 4, 5, & 6 should be under the above section "Set up your app"

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +1. Add the following app to your list of ```INSTALLED_APPS``` in your ColdFront **base.py** file:
```suggestion
1. Add the following app to your list of ```INSTALLED_APPS``` in the ColdFront **base.py** (`coldfront/config/base.py`) file:
```

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +2. Edit your main ColdFront **urls.py** file to include the new urls:
```suggestion
2. Edit the ColdFront **urls.py** (`coldfront/config/urls.py`) file to include the new urls info:
```

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +2. Ensure that your **__init__.py** file contents have the following format:
```suggestion
2. Ensure that your app's **__init__.py** file contents have the following format:
```

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +3. Ensure that your **apps.py** file contents look like this:
```suggestion
3. Ensure that your app's **apps.py** file contents look like this:
```

2023-06-23 18:40 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +4. Make sure to include this line in your **urls.py** file!
```suggestion
4. Make sure to include this line in your app's **urls.py** file:
```

2023-06-27 19:36 UTC, dsajdak commented on docs/pages/plugin/how_to_create_a_plugin.md
> +1. Add the following app to your list of ```INSTALLED_APPS``` by creating a new file in the ColdFront plugins directory (`coldfront/plugins`) and adding these lines to the new file:
```suggestion
1. Add the following app to your list of ```INSTALLED_APPS``` by creating a new file in the ColdFront plugins directory (`coldfront/congig/plugins`) and adding these lines to the new file (i.e. `weeklyreportapp.py`):
```

2023-07-21 01:18 UTC, aebruno requested changes
just need to fix up .gitignore. otherwise looks good

2023-07-21 01:18 UTC, aebruno commented on .gitignore
> +coldfront/core/allocation/migrations/0006_auto_20230607_1719.py
Not sure why all these are getting added to `.gitignore`. Lets remove these.

2023-07-24 21:31 UTC, rg663 commented on .gitignore
> +coldfront/core/allocation/migrations/0006_auto_20230607_1719.py
Fixed @aebruno!

2023-07-26 01:24 UTC, aebruno approved these changes

2023-07-26 01:25 UTC, merged