Grants formatting error fixed
ubccr/coldfront pull request #533
Opened 2023-06-10 01:44 UTC by rg663

Resolves issue #442 — Grant amounts in the grant creation/ editing form can now be entered with dollar signs and commas, and percents can be entered with percent signs. In the grant report and project detail pages, grant amounts and percentages are also formatted to be rounded to two decimal places for consistency.

2023-06-23 19:17 UTC, dsajdak requested changes
@rg663 I tried a few different combinations of dumb things to break this and was able to.  Since I'm not seeing the help text I pretended not to know what types of numbers to use in this boxes.  If I enter, for example '5%' in the 'direct funding' box I get an ugly error.  I tried a few other things that would just be accidental typos like "$5%" or "5 000" and got the ugly errors:
`<html>
<body>
<!--StartFragment-->

Exception Type: | ValueError
-- | --
could not convert string to float: '5%'

<!--EndFragment-->
</body>
</html>`

It would be good to have nice error messages that ask the user to format correctly.

2023-06-23 19:17 UTC, dsajdak commented on coldfront/core/grant/forms.py
> +            'percent_credit': 'Percent credit as entered in the sponsored projects form for grant submission as financial credit to the department/unit in the credit distribution section. Only digits
I'm not seeing this help text.  Is this browser specific?

2023-06-26 16:11 UTC, rg663 commented on coldfront/core/grant/forms.py
> +            'percent_credit': 'Percent credit as entered in the sponsored projects form for grant submission as financial credit to the department/unit in the credit distribution section. Only digits
<img width="743" alt="Screenshot 2023-06-26 at 12 07 42" src="https://github.com/ubccr/coldfront/assets/74742605/9a5d00cb-009a-413b-8263-4f9904f89b2c">

@dsajdak Thank you for bringing this to my attention! These fields all have better error messages now like in the screenshot above. About the help text, from what I observed, it only shows up when creating a new grant but not when updating a grant's info. Is it the same on your end?

2023-07-21 01:09 UTC, aebruno requested changes
This doesn't seem to work for me. To test I added a grant and entered $1.00 for Direct Funding and $2.00 for Total award amount. After submitting the form the values stored in the database were 100.0 and 200.0 respectively.

2023-07-21 01:09 UTC, aebruno commented on .gitignore
> +coldfront/core/allocation/migrations/0006_auto_20230607_1719.py
This shouldn't be here. Lets remove this line.

2023-07-24 21:32 UTC, rg663 commented on .gitignore
> +coldfront/core/allocation/migrations/0006_auto_20230607_1719.py
Fixed @aebruno

2023-07-26 01:49 UTC, aebruno approved these changes

2023-07-26 01:49 UTC, merged