fix misfiring success message, remove redundant function
ubccr/coldfront pull request #557
Opened 2023-07-28 22:14 UTC by claire-peters

Learned earlier today that the post function for the AllocationCreateView was the wrong way to add a success message - it presents the success message even when an error is present on the form. This push corrects that error. It also contains the removal of an unneeded method - the AllocationAddInvoiceNoteView had two get_context_data methods and the second one is the one that would have been in operation, so I deleted the first.

2023-07-29 16:58 UTC, aebruno requested changes

2023-07-29 16:58 UTC, aebruno commented on coldfront/core/allocation/views.py
> -    def get_context_data(self, **kwargs):
I believe we want to keep this function has it contains all the business logic? and delete the other one?

2023-07-31 18:36 UTC, claire-peters commented
I kept the second because it's the only one that's actually been in use - you can see in [the commit where the first was added](https://github.com/ubccr/coldfront/blob/8e64bfa1ddc8deee870f0baa927c63e095044a9a/coldfront/core/allocation/views.py#L1502-L1550) that it was all added preceding the second get_context_data method, meaning this code has never actually run. I can't really attest to the business logic of the new method for that reason, so I went with the one that's been in use.

That said, I'm happy to instead test the new/first get_context_data function, make sure it works, and remove the older function. Just let me know!

2023-08-02 22:45 UTC, claire-peters commented
An additional observation makes the solution even easier - the business logic in the longer get_context_data method is taken straight from AllocationDetailView and has no business being in the AllocationAddInvoiceNoteView class. The second method is definitely the right one.

2023-08-03 02:36 UTC, aebruno commented
> An additional observation makes the solution even easier - the business logic in the longer get_context_data method is taken straight from AllocationDetailView and has no business being in the AllocationAddInvoiceNoteView class. The second method is definitely the right one.

@claire-peters Thanks, yes just noticed this as well. Looks good to me!

2023-08-03 02:36 UTC, aebruno approved these changes

2023-08-03 02:36 UTC, merged