Updates to support TLS in ldap_user_search plugin
ubccr/coldfront pull request #643
Opened 2024-12-10 19:11 UTC by payerle

This PR should address concerns of #631

Basically:
1) Adds new config parameter LDAP_USER_SEARCH_CERT_VALIDATE_MODE which is passed to the ldap3.Tls constructor as validate. Accepts as values:
	'required' : Certs are required and must validate
	'optional' : Certs are optional, but must validate if provided
	'none' (or None): Certs are ignored.
The default is None

2) The LDAP_USER_SEARCH_CERT_VALIDATE_MODE is passed as the validate field to the ldap3.Tls constructor

3) If LDAP_USE_TLS is set, we pass the connection parameter 'auto_bind' as ldap3.AUTO_BIND_TLS_BEFORE_BIND instead of simply True Inspection of ldap3 code shows that when this parameter is set to True (a value which is no longer listed in docs as valid) it is treated as AUTO_BIND_NO_TLS, so the previous before of leaving this as True was not doing TLS despite claiming to do TLS. This fix should change that.

2024-12-10 19:13 UTC, payerle commented
The above PR should address this issue.  Running under coldfront runserver with same config file, the tcpdump shows the LDAP query as encrypted.  When repeated with bind_dn and passwd, the encryption is starting before the bind.

2025-04-14 02:25 UTC, aebruno requested changes
@payerle This looks good thanks for the PR. One minor code change requested. Also, we require all commits to be "Signed-off" by using git commit --signoff which will acknowledge that you agree to the [DCO](https://github.com/ubccr/coldfront/blob/main/DCO.md). Can you rebase/add --signoff. Make sure it's a single commit. Thank you!

2025-04-14 02:25 UTC, aebruno commented on coldfront/plugins/ldap_user_search/utils.py
> +            if self.LDAP_CERT_VALIDATE_MODE == 'none':
This first case is not necessary. Change simplify to:
```
            if self.LDAP_CERT_VALIDATE_MODE == 'optional':
                ldap_cert_validate_mode = ssl.CERT_OPTIONAL
            elif self.LDAP_CERT_VALIDATE_MODE == 'required':
                ldap_cert_validate_mode = ssl.CERT_REQUIRED
```

2025-06-01 03:25 UTC, aebruno commented
This has been replaced by #683

2025-06-01 03:25 UTC, closed without merging